[package]
name = "bevy_minibuffer"
version = "0.1.0-alpha.1"
edition = "2021"

[dependencies]
bevy = "0.13"
bitflags = "2.3.1"
futures-lite = "1.13.0"
promise_out = "1.0.0"
trie-rs = { git = "https://github.com/shanecelis/trie-rs.git", branch = "add-iterators-and-inc-search" }
colored = { version = "2.0.0", features = [ "no-color" ] }
bevy-input-sequence = { version = "0.3.0", path = "../bevy-input-sequence" }
keyseq = { version = "0.2.2", features = [ "bevy" ], path = "../keyseq" }
asky = { version = "0.1.1", path = "../asky", default-features = false, features = ["bevy"] }
text-style = { path = "../text-style-rs", features = [ "crossterm", "bevy" ] }
bevy_crossbeam_event = "0.5.0"
tabular = "0.2.0"
thiserror = "1.0.58"

[dev-dependencies]
bevy-inspector-egui = "0.23.4"
# bevy_editor_pls = { path = "../bevy_editor_pls/crates/bevy_" }
