[package]
name = "bevy-nano-console"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.12.0"
# bevy = { git = "https://github.com/bevyengine/bevy.git" }
bitflags = "2.3.1"
# changed = "0.1.2"
futures-lite = "1.13.0"
nano-macro = { version = "0.1.0", path = "nano-macro" }
promise_out = { git = "https://github.com/shanecelis/promise_out.git" }
trie-rs = "0.1.1"
colored = { version = "2.0.0", features = [ "no-color" ] }
