[package]
name = "bevy_minibuffer"
version = "0.1.0-alpha.1"
edition = "2021"

[dependencies]
bevy = "0.14"
bitflags = "2.3.1"
trie-rs = "0.4.2"
bevy-input-sequence = "0.5.0"
keyseq = { version = "0.3", features = [ "bevy" ]}
bevy_asky = { path = "../bevy_asky", features = [ "async" ] }
futures = { version = "0.3.30", optional = false }
tabular = "0.2.0"
thiserror = "1.0.58"
bevy_defer = "0.12"

[dev-dependencies]
bevy-inspector-egui = "0.25"

[patch.crates-io]
