[package]
name = "bevy-nano-console"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.0"
bitflags = "2.3.1"
futures-lite = "1.13.0"
promise_out = "1.0.0"
trie-rs = { path = "../trie-rs" }
colored = { version = "2.0.0", features = [ "no-color" ] }
bevy-input-sequence = { version = "0.3.0", path = "../bevy-input-sequence" }
keyseq = { version = "0.2.2", features = [ "bevy" ], path = "../keyseq" }
asky = { version = "0.1.1", path = "../asky", default-features = false, features = ["bevy"] }
text-style = { path = "../text-style-rs", features = [ "crossterm", "bevy" ] }
bevy_crossbeam_event = "0.5.0"
