[package]
name = "bevy_minibuffer"
version = "0.1.0-alpha.1"
edition = "2021"

[dependencies]
bevy = "0.13"
bitflags = "2.3.1"
futures-lite = "1.13.0"
promise_out = "1.0.0"
trie-rs = { git = "https://github.com/shanecelis/trie-rs.git", branch = "dev" }
colored = { version = "2.0.0", features = [ "no-color" ] }
bevy-input-sequence = { git = "https://github.com/shanecelis/bevy-input-sequence.git", branch = "dev" }
keyseq = { version = "0.2.3", features = [ "bevy" ]}
asky = { git = "https://github.com/shanecelis/asky.git", branch = "bevy", default-features = false, features = ["bevy"] }
text-style = { git = "https://github.com/shanecelis/text_style.git", branch = "feature/colored", features = [ "crossterm", "bevy" ] }
bevy_crossbeam_event = "0.5.0"
tabular = "0.2.0"
thiserror = "1.0.58"

[dev-dependencies]
bevy-inspector-egui = "0.23.4"
# bevy_editor_pls = { path = "../bevy_editor_pls/crates/bevy_" }
