[package]
name = "bevy-nano-console"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.0"
bitflags = "2.3.1"
futures-lite = "1.13.0"
promise_out = "1.0.0"
trie-rs = "0.1.1"
colored = { version = "2.0.0", features = [ "no-color" ] }
bevy-input-sequence = "0.3.0"
keyseq = { version = "0.2.2", features = [ "bevy" ] }
