[package]
name = "bevy_minibuffer"
version = "0.1.0-alpha.1"
edition = "2021"

[dependencies]
bevy = "0.14"
bitflags = "2.3.1"
trie-rs = "0.4.2"
bevy-input-sequence = "0.5.0"
keyseq = { version = "0.3", features = [ "bevy" ]}
bevy_asky = { git = "https://github.com/shanecelis/bevy_asky.git", default-features = false }
futures = { version = "0.3.30", optional = true }
tabular = "0.2.0"
thiserror = "1.0.58"
bevy_defer = { version = "0.12", optional = true }
# bevy_crossbeam_event = { version = "0.6.0", optional = true }
bevy_channel_trigger = { version = "0.2.0", optional = true }

[features]
async = [ "dep:bevy_defer", "dep:futures", "bevy_asky/async", "dep:bevy_channel_trigger" ]

[dev-dependencies]
bevy-inspector-egui = "0.25"

[patch.crates-io]

[[example]]
name = "simplest-async"
path = "examples/async/simplest.rs"
required-features = [ "async" ]

[[example]]
name = "basic-async"
path = "examples/async/basic.rs"
required-features = [ "async" ]

[[example]]
name = "demo-async"
path = "examples/async/demo.rs"
required-features = [ "async" ]

[[example]]
name = "cube-async"
path = "examples/async/cube.rs"
required-features = [ "async" ]

[[example]]
name = "two-commands-async"
path = "examples/async/two_commands.rs"
required-features = [ "async" ]
